config/routes.rb
HelloApp::Application.routes.draw do

  resources :keywords
  root 'static_pages#home'
  get '/home',  to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/feedback', to: 'static_pages#feedback'
  get '/contact', to: 'static_pages#contact'

  resources :reviews, path: 'papers/:paper_id/reviews'
  get    '/reviews/mine' => 'reviews#mine', :as => :user_reviews
  post   'papers/:paper_id/review_opinion' => 'reviews#validate_opinion', :as => :review_opinion

  get   'papers/:paper_id/accept' => 'reviews#accept', :as => :accept_paper
  get   'papers/:paper_id/refuse' => 'reviews#refuse_notif', :as => :refuse_paper_notif
  post   'papers/:paper_id/refuse' => 'reviews#refuse', :as => :refuse_paper
  get   'papers/:paper_id/ask_revision' => 'reviews#ask_revision_notif', :as => :ask_paper_revision_notif
  post   'papers/:paper_id/ask_revision' => 'reviews#ask_revision', :as => :ask_paper_revision

  get  'papers/:paper_id/finished' => 'papers#signal_edition_finished', :as => :signal_edition_finished

  resources :people
  get   '/people/:id/edit_password' => 'people#edit_password', :as => :edit_password
  post  '/people/:id/edit_password' => 'people#update_password'
  get   '/people/:id/papers' => 'people#papers', :as => :user_papers

  get   '/signup',  to: 'people#new'
  post  '/signup',  to: 'people#create'
  resources :account_activations#, only: [:edit]

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get   '/people/:id/activate' => 'people#activate', :as => :person_activate

  get 'papers/pending', to:  'papers#index_pending'
  get 'papers/all',     to:  'papers#index_all'
  get 'papers/refused', to:  'papers#index_refused'
  resources :papers

  resources :categories

  get 'reading_lists/public', to: 'reading_lists#index_public'
  resources :reading_lists

  get 'reading_list_saves/:paper_id',
    to:   'reading_list_saves#save_default',
    :as => :reading_list_save_default
  get 'reading_list_saves/:reading_list_id/:paper_id',
    to:   'reading_list_saves#save',
    :as => :reading_list_save
  get 'reading_list_remove/:reading_list_id/:paper_id',
    to:   'reading_list_saves#remove',
    :as => :reading_list_remove

end

app/models/paper.rb
class Paper < ApplicationRecord
  belongs_to :category

  # min_reviews = Rails.configuration.options['reviews']['min_reviews']
  # max_reviews = Rails.configuration.options['reviews']['max_reviews']

  #   AUTHORS

  # Get all authors of a paper
  def get_authors
    Author.where(paper_id: id).map { |author|
      Person.where(id: author.person_id).take
    }
  end

  # Format the list of authors
  # Params:
  # +initials+::  +bool+  true: get only the initial of the firstname
  def get_authors_as_name_list(initials: false)
    list = self.get_authors.map { |author|
      author.full_name(initials)
    }
    list.join(', ')
  end

  # Key keywords for a paper
  def get_keywords
    Keyword.where(paper_id: id).all
  end

  #####################################
  # REVIEWS
  #####################################

  def get_reviews
    Review.where(paper_id: id).all
  end

  def get_last_reviews
    Review.where(
      paper_id: id,
      review_round: reviews_count
    ).all
  end

  def last_done_reviews
    Review.where(
      paper_id: id,
      review_round: reviews_count,
      progression: 'done'
    ).all
  end

  def get_reviewers
    Review.where(paper_id: id).map { |reviews|
      Person.where(id: reviews.reviewer_id).take
    }
  end

  # Get the review for a given paper and person
  def get_review_by(person)
    Review.where(paper_id: self[:id], reviewer_id: person.id).take
  end


  # REVIEW PROCESS
  ################

  # Returns true if the paper should be reviewed:
  #  * if it is not already accepted
  #  * if its type is reviewable (not an opinion paper for example)
  #  * if it doesn't have <max_reviews> reviews already
  def can_be_reviewed?
    paper_type != 'opinion' &&
        is_under_review? &&
        self.count_reviews < 4
  end

  # Count all the reviews a paper have (all status and progression)
  def count_reviews
    self.get_reviews.count
  end

  # Count the "current" reviews a paper have
  def count_last_reviews
    self.get_last_reviews.count
  end

  # Does the paper have any reviews ?
  def has_reviews?
    self.count_reviews > 0
  end

  # Checks if a paper has more than <min_reviews> reviews,
  #   and all of them are done
  def all_reviews_done?
    reviews = self.get_reviews
    total = reviews.count
    total >= 2 && reviews.where(progression: 'done').count == total
  end

  # Review starteted
  def reviews_started?
    Review.where(paper_id: id, progression: ['ongoing', 'done']).count > 0
  end

  # Returns an average (in %) of the reviews
  # only to indicate the amount of modification that will have to be done
  def get_reviews_score
    (self.get_reviews.average(:status) * 100) / 3
  end

  def signal_edition_finished
    self.set_to_review
  end


  # review STATUS
  ################

  def is_pending_opinion?
    paper_type == 'opinion' && status < 2
  end

  # CALCULATE A PAPER STATUS ACCORDING TO REVIEWS
  def current_reviews_round_done
    Review.where(paper_id: id, review_round: reviews_count)
    self.update(status: 1) if self.all_reviews_done?
  end

  def add_a_review_round
    self.update(reviews_count: reviews_count+1)
  end

  # Are all the reviews finished ?
  def should_be_reviewed?
    need_review == 1
  end

  def set_to_review
    self.update(need_review: 1)
  end

  def set_review_round_done
    self.update(need_review: 0)
  end

  # if the paper is not yet published nor refused, all reviews are done, and the editor says
  def need_revision?
    self.status < 2 && ! should_be_reviewed?
  end

  # if the paper is published, and does not have any reviews, or still needs review
  def have_problem_in_review
    (status == 2 || status == 3) && (reviews_count < 1 || need_review)
  end

  #####################################
  # state STATUS
  #####################################

  def publish
    self.update(status: 2)
  end

  def refuse
    self.update(status: 3)
  end

  def is_pending_waiting?
    status == -1
  end

  def is_pending?
    status == 0
  end

  def is_pending_done?
    status == 1
  end

  def is_pending?
    status == 0
  end

  def is_pending_done?
    status == 1
  end

  def is_published?
    status == 2
  end

  def is_refused?
    status == 3
  end

  def is_under_review?
    status < 2
  end

end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
  before_action :set_paper,        only: [:show, :edit, :update, :destroy]

  # permissions to access
  before_action :logged_in_author, only: [:edit, :update, :destroy]
  before_action :is_researcher,    only: [:new, :create]
  before_action :is_editor,        only: [:index_pending, :index_refused, :index_all, :validate, :refuse]

  # GET /papers
  def index
    @title = "Published papers"
    @papers = Paper.where(status: 2)
  end

  # GET /papers/pending
  def index_pending
    @title = "Pending papers"
    @papers = Paper.where(status: [-1, 0, 1])
    render :index
  end

  # GET /papers/refused
  def index_refused
    @title = "Refused papers"
    @papers = Paper.where(status: 3)
    render :index
  end

  # GET /papers/all
  def index_all
    @title = "All papers"
    @papers = Paper.all
    render :index
  end


##########################################################

  # GET /papers/1
  # GET /papers/1.json
  def show
  end

  # GET /papers/new
  def new
    @paper = Paper.new
  end

  # GET /papers/1/edit
  def edit
  end


##########################################################

  # POST /papers
  def create
    @paper = Paper.new(paper_params)
    @paper.status = -1 # pending & not reviewed
    @paper.reviews_count = 0

    if @paper.save
      # save current_user as author
      Author.create(paper_id: @paper.id, person_id: current_user.id, status: 'author')
      # save other co-authors
      params[:authors].each { |coauth|
        Author.create(paper_id: @paper.id, person_id: coauth, status: 'co-author')
      }

      # save keywords
      # keywords
      JSON.parse params[:keywords].each { |kw|
        Keyword.create(name: kw, paper_id: @paper.id)
      }

      redirect_to @paper, notice: t('paper.creates.success')
    else
      render :new
    end
  end

  # PATCH/PUT /papers/1
  def update
    if @paper.update(paper_params)
      redirect_to @paper, notice: t('paper.update.success')
    else
      render :edit
    end
  end

  # DELETE /papers/1
  def destroy
    @paper.destroy
    redirect_to papers_url, notice: t('paper.delete.success')
  end

  ###################################################

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_paper
      @paper = Paper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paper_params
      params.require(:paper).permit(
      :paper_type, :title, :abstract, :status, :publication_date, :tex_content, :html_content, :pdf_url, :category_id, :uuid, :conflict_of_interest, :licence, :doi, :keywords, :accepted_at, :reviews_count, :need_review
      )
    end

    def author_params
      params.require(:paper_id, :person_id)
    end

    def logged_in_author
      if !logged_in?
        store_location
        redirect_to login_url, :flash => { :error => t('people.unauthorized') }
      elsif !@paper.get_authors.include? current_user
        redirect_to @paper, :flash => { :error => t('paper.edit.forbidden') }
      end
    end

end

app/helpers/papers_helper.rb
module PapersHelper

  # Get the authors-of-a-paper IDs
  def get_authors_id(paper)
    paper.get_authors.pluck(:id)
  end

  # Get the reviewers-of-a-paper IDs
  def get_reviewers_id(paper)
    paper.get_reviewers.pluck(:id)
  end

  # Get the list of possible paper types
  def get_paper_types
    [
      'research article',
      'thesis',
      'letter',
      'clinical case study',
      'clinical trial',
      'opinion',
      'review', # can be a public review on an article: no
      'other',
      # 'technical report'
    ]
  end


  def get_paper_status(status)
    case status
    when -1
      'pending (not reviewed)'
    when 0
      'pending (being reviewed)'
    when 1
      'pending (reviewed)'
    when 2
      'published' # accepted
    when 3
      'refused'
    end
  end

  # Get researcher who did not wrote the paper, and are not already  reviewing it
  def get_possible_reviewers_for(paper)
    Person
      .where(status: 'researcher')
      .where.not(id: get_authors_id(paper))
      .where.not(id: get_reviewers_id(paper))
      .all
  end


  def licence_choice
    [
      'CC BY SA',
      'MIT',
      'GNU',
      '...'
    ]
  end

end

app/views/papers/partials/_paper_list.html.erb
<div class="row">

<% papers.each do |paper| %>
<!-- - - - - - - - - - - - - - - - - PAPER - - - - - - - - - - - - - - - - - - -->
  <div class="card col m8 offset-m2">
  <div class="card-content">

  <span class="title">
    <%= "#{icon_warning}".html_safe if paper.need_revision? %>

    <% if paper.is_refused? %>
    <span class="red-text"><strong>[Refused]</strong></span>
    <% elsif paper.is_pending_waiting? %>
    <span class="grey-text"><strong>[Pending]</strong></span>
    <% end %>
    <%= link_to paper.title, paper %>
  </span>

  <div class="right right-align">
    <%= render 'reading_lists/partials/save_button', :paper => paper if logged_in? %>
    <small>
      <p><%= paper.category.name if paper.category %></p>
      <p><%= paper.created_at.strftime("%d %B %Y") %></p>
    </small>
  </div>

  <p>
    <span itemprop="authors">
      <% paper.get_authors.each do |author| %>
      <%= author.full_name %>
      <% end %>
    </span>
  </p>

<% if logged_in?  %>
  <%= link_to "Review n. #{paper.reviews_count}", reviews_path(paper.id) if paper.reviews_count %>
  <%= render 'reviews/partials/short_preview', :reviews => paper.get_last_reviews %>
  <%= link_to 'Review the paper', paper if paper.all_reviews_done? %>
<% end %>

  </div>
</div>
<% end %>

</div>

app/views/papers/partials/_show_review_process.html.erb
<div class="reviews-process">

<%= # EDITOR: ASK REVIEWS

if current_user.is_editor?

  if @paper.all_reviews_done?
    render 'reviews/partials/validate'
  elsif @paper.can_be_reviewed?
    render 'reviews/partials/new'
  elsif @paper.is_pending_opinion?  # EDITOR: IF OPINION, ONLY VALIDATE
    render 'reviews/partials/new_opinion'
  end

end  %>

<% # AUTHOR
if current_user.wrote?(@paper) && @paper.all_reviews_done? %>

<div class="row">
  <h3>Your paper has been reviewed.</h3>
  <div class="col l3 m12 s12">
    <p> Read the reviews </p>
    <p><%= link_to 'Read the reviews', reviews_path(@paper.id), class: "btn" %></p>
  </div>
  <div class="col l3 m6 s12">
    <p>Please read the reviews and update your paper consequently.</p>
    <p><%= link_to 'Update your paper', edit_paper_path(@paper), class: "btn" %></p>
  </div>
  <div class="col l3 m6 s12">
    <p>Once your paper is edited, please ask the editor to review it again</p>
    <p><%= link_to 'Signal correction finished ', signal_edition_finished_path(@paper), class: "btn" %></p>
  </div>
  <div class="col l3 m6 s12">
    <p>You can ask the editor questions if you have any questions</p>
    <p><a href="#" class="btn">Ask</a><%#= link_to 'Ask', ask_editor_about(@paper), class: "btn" %></p>
  </div>
</div>




<%   #  REVIEWER
elsif current_user.should_review?(@paper) %>

  <%= link_to 'Start reviewing',
    edit_review_path(@paper.id, @paper.get_review_by(current_user)),
    class: "btn color2bg" %>

<% elsif current_user.is_reviewing?(@paper) %>

  <%= link_to 'Continue or edit your review',
    edit_review_path(@paper.id, @paper.get_review_by(current_user)),
    class: "btn color2bg" %>

<% elsif current_user.reviewed?(@paper) %>

  <%= link_to 'See your review',
    review_path(@paper.id, @paper.get_review_by(current_user)),
    class: "btn" %>

    <% end  # end reviews %>

</div>