config/routes.rb
HelloApp::Application.routes.draw do

  resources :keywords
  root 'static_pages#home'
  get '/home',  to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/feedback', to: 'static_pages#feedback'
  get '/contact', to: 'static_pages#contact'

  resources :reviews, path: 'papers/:paper_id/reviews'
  get    '/reviews/mine' => 'reviews#mine', :as => :user_reviews
  post   'papers/:paper_id/review_opinion' => 'reviews#validate_opinion', :as => :review_opinion

  get   'papers/:paper_id/accept' => 'reviews#accept', :as => :accept_paper
  get   'papers/:paper_id/refuse' => 'reviews#refuse_notif', :as => :refuse_paper_notif
  post   'papers/:paper_id/refuse' => 'reviews#refuse', :as => :refuse_paper
  get   'papers/:paper_id/ask_revision' => 'reviews#ask_revision_notif', :as => :ask_paper_revision_notif
  post   'papers/:paper_id/ask_revision' => 'reviews#ask_revision', :as => :ask_paper_revision

  get  'papers/:paper_id/finished' => 'papers#signal_edition_finished', :as => :signal_edition_finished

  resources :people
  get   '/people/:id/edit_password' => 'people#edit_password', :as => :edit_password
  post  '/people/:id/edit_password' => 'people#update_password'
  get   '/people/:id/papers' => 'people#papers', :as => :user_papers

  get   '/signup',  to: 'people#new'
  post  '/signup',  to: 'people#create'
  resources :account_activations#, only: [:edit]

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get   '/people/:id/activate' => 'people#activate', :as => :person_activate

  get 'papers/pending', to:  'papers#index_pending'
  get 'papers/all',     to:  'papers#index_all'
  get 'papers/refused', to:  'papers#index_refused'
  resources :papers

  resources :categories

  get 'reading_lists/public', to: 'reading_lists#index_public'
  resources :reading_lists

  get 'reading_list_saves/:paper_id',
    to:   'reading_list_saves#save_default',
    :as => :reading_list_save_default
  get 'reading_list_saves/:reading_list_id/:paper_id',
    to:   'reading_list_saves#save',
    :as => :reading_list_save
  get 'reading_list_remove/:reading_list_id/:paper_id',
    to:   'reading_list_saves#remove',
    :as => :reading_list_remove

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_home.html.erb
<%# DEFAULT HOME %>
<div class="row">
  <div class="col offset-l2 l7 m8 s12">
    <div class="landing-title">

      <%= image_tag("heptagon_blue.svg", size: "200", class: 'title-heptagon') %>
      <h1>
        <span> open science </span>
      </h1>

      <h3 class="color1 strong">open access scientific revue</h3>

      <h4 class="text-grey darken-3 strong">free publishing for researchers</h4>
      <h4 class="text-grey darken-3">free reading for the public</h4>
      <h3 class="color2 strong">community based peer review</h3>

    </div>
  </div>

  <div class="col m2 s12">

    <div class="center-align" style="text-align: center; padding-top: 3em;">
      <%= link_to "Log in", login_path, class: 'btn-large color1bg' %>
      <p>or</p>
      <%= link_to "Sign up", signup_path, class: 'btn-large color2bg' %>
    </div>

  </div>
</div>


<div class="row landing-text">

  <div class="background-paral"></div>

  <div class="col m4">
    We allow researcher to publish freely, as we believe good science should be made available without fees.
  </div>
  <div class="col m4">
    We guarantee a quality of work and conflict-free reviews, by a community based peer reviewed, automation to help the process, while helping respecting the anonymysity but promoting transparence during the process.
  </div>
  <div class="col m4">
    The public is allowed to access the works as they are foundation of our society blabla bla.
  </div>
</div>

app/views/static_pages/_home_admin.html.erb
<%
  provide(:title, "Admin #{@current_user.firstname}")
%>

<div class="row">
  <div class="col m8">
    <p>TODO: backend for managing</p>
    <h2>Welcome <%= @current_user.firstname %> (admin)</h2>

    <h3>papers</h3>
    There is currently <%= Paper.all.count %> articles.

    <h3>reviews</h3>

  </div>

  <div class="col m4">

    <div class="input-field">
      <label for="search">
        <i class="material-icons prefix">search</i>
      </label>
      <input id="search" type="search" placeholder="Search an article, an author, a keyword…">
    </div>

    <h3>Papers</h3>
    <p> <%= link_to 'All', papers_all_path, class: 'btn-flat' %> </p>
    <p> <%= link_to 'Pending', papers_pending_path, class: 'btn-flat' %> </p>
    <p> <%= link_to 'Refused', papers_refused_path, class: 'btn-flat' %> </p>
    <p> <%= link_to 'Published', papers_path, class: 'btn-flat' %> </p>

  </div>
</div>

app/views/static_pages/_home_editor.html.erb
<%
  provide(:title, "Welcome #{@current_user.firstname}")
  @pending_reviews = current_user.get_pending_reviews_asked_by_editor
%>

<div class="row">
  <div class="col s8">
    <h2> Welcome <%= @current_user.firstname %></h2>

    <h3>Latest articles</h3>
    <blockquote>
      Here is a list of the last articles published that might interest you
    </blockquote>

    <h3>Reviews you asked</h3>
    <% if @pending_reviews.count > 0 %>
      Find below the works currently reviewed under your supervision:
    <%= render 'reviews/partials/review_list', :reviews => @pending_reviews, :from => 'home_editor' %>
    <% else %>
    You have no pending reviews on your supervision.
    <% end %>

  </div>

  <div class="col s4">

    <div class="input-field">
      <label for="search">
        <i class="material-icons prefix">search</i>
      </label>
      <input id="search" type="search" placeholder="Search an article, an author, a keyword…">
    </div>

    <h3>Papers</h3>
    <p> <%= link_to 'All', papers_all_path, class: 'btn-flat' %> </p>
    <p> <%= link_to 'Pending', papers_pending_path, class: 'btn-flat' %> </p>
    <p> <%= link_to 'Refused', papers_refused_path, class: 'btn-flat' %> </p>
    <p> <%= link_to 'Published', papers_path, class: 'btn-flat' %> </p>

  </div>
</div>

app/views/static_pages/_home_reader.html.erb
<%
  provide(:title, "Welcome #{@current_user.firstname}")
%>

<div class="row">
  <div class="col s8">
    <h2> Welcome <%= @current_user.firstname %></h2>

    <h3>Latest articles</h3>
    <blockquote>
      Here is a list of the last articles published that might interest you
    </blockquote>

  </div>

  <div class="col s4">

    <div class="input-field">
      <label for="search">
        <i class="material-icons prefix">search</i>
      </label>
      <input id="search" type="search" placeholder="Search an article, an author, a keyword…">
    </div>

  </div>
</div>

app/views/static_pages/_home_researcher.html.erb
<%
  provide(:title, "Welcome #{@current_user.firstname}")
  @pending_reviews = current_user.get_pending_reviews
%>

<div class="row">
  <div class="col s8">
    <h2> Welcome <%= @current_user.firstname %></h2>

    <h3>Latest articles</h3>
    <blockquote>
      Here is a list of the last articles published that might interest you
    </blockquote>

    <h3>Your current reviews</h3>
    <% if @pending_reviews.count > 0 %>
      Find below the works you are currently reviewing
    <%= render 'reviews/partials/review_list', :reviews => @pending_reviews, :from => 'home_reviewer' %>
    <% else %>
    You have no pending reviews !
    <% end %>

  </div>

  <div class="col s4">

    <div class="input-field">
      <label for="search">
        <i class="material-icons prefix">search</i>
      </label>
      <input id="search" type="search" placeholder="Search an article, an author, a keyword…">
    </div>

    <p><%= link_to 'Publish a paper', new_paper_path, class: 'btn-large color2bg' %></p>

    <p>
      <%= link_to 'your reviews', user_reviews_path, class: 'btn-flat' %>
    </p>
    <p>
      <%= link_to 'your articles', user_papers_path(@current_user.id), class: 'btn-flat' %>
    </p>

  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<p>Scientific publications in open-access</p>

<h3>Functionalities</h3>
<ul class="collection">
    <li>Automatization of peer review process, to allow a scientific journal to be open-access.</li>
</ul>

<h3>Workflow</h3>
<ul class="collection">
    <li>Researchers can submit their papers</li>
    <li>Editors propose to associate the paper with 2 or 3 researchers for peer review</li>
    <li>During the review process, the article is shown as 'in preparation' and can't be read</li>
    <li>The reviews are compared, then the article can be accepted or rejected.</li>
    <li>If the peer reviews are okay, the submitter can read the reviews and correct the article</li>
    <li>After validation of the corrections, the article is published</li>
</ul>



<h3> todo </h3>
<ul class="collection">
  <li>See trello</li>
  <!--
  <li></li>
  -->
</ul>

<h3>How to</h3>
<ul class="collection">
  <li></li>
</ul>

<h3>Links</h3>
<div class="collection">
  <a class="collection-item" href="https://doaj.org/">Directory of Open Access Journals (DOAJ)</a>
  <a class="collection-item" href="https://hal.archives-ouvertes.fr/">HAL</a>
  <a class="collection-item" href="https://arxiv.org/">Arxiv</a>
  <!--
  <a class="collection-item" href=""></a>
  -->
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>

<form action="<%= contact_path %>" method="get">


<label for="object">Object</label>
<input type="text" id="object" name="object">

<label for="message">Your message</label>
<textarea name="message" id="message" Your messagecols="30" rows="10" class="materialize-textarea" length="2000"></textarea>

<input type="submit" class="btn" value="Send">


</form>

app/views/static_pages/feedback.html.erb
<div class="feedback-message">

  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
  <% end %>

</div>

app/views/static_pages/home.html.erb
<%# TODO provide(:title, "[x notifs]") %>

<%=
if logged_in?

    if current_user.is_researcher?
      render 'static_pages/home_researcher'
    elsif current_user.is_admin?
      render 'static_pages/home_admin'
    elsif current_user.is_editor?
      render 'static_pages/home_editor'
    else
      render 'static_pages/home_reader'
   end

else

  render 'static_pages/home'

end
%>