config/routes.rb
HelloApp::Application.routes.draw do

  resources :keywords
  root 'static_pages#home'
  get '/home',  to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/feedback', to: 'static_pages#feedback'
  get '/contact', to: 'static_pages#contact'

  resources :reviews, path: 'papers/:paper_id/reviews'
  get    '/reviews/mine' => 'reviews#mine', :as => :user_reviews
  post   'papers/:paper_id/review_opinion' => 'reviews#validate_opinion', :as => :review_opinion

  get   'papers/:paper_id/accept' => 'reviews#accept', :as => :accept_paper
  get   'papers/:paper_id/refuse' => 'reviews#refuse_notif', :as => :refuse_paper_notif
  post   'papers/:paper_id/refuse' => 'reviews#refuse', :as => :refuse_paper
  get   'papers/:paper_id/ask_revision' => 'reviews#ask_revision_notif', :as => :ask_paper_revision_notif
  post   'papers/:paper_id/ask_revision' => 'reviews#ask_revision', :as => :ask_paper_revision

  get  'papers/:paper_id/finished' => 'papers#signal_edition_finished', :as => :signal_edition_finished

  resources :people
  get   '/people/:id/edit_password' => 'people#edit_password', :as => :edit_password
  post  '/people/:id/edit_password' => 'people#update_password'
  get   '/people/:id/papers' => 'people#papers', :as => :user_papers

  get   '/signup',  to: 'people#new'
  post  '/signup',  to: 'people#create'
  resources :account_activations#, only: [:edit]

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get   '/people/:id/activate' => 'people#activate', :as => :person_activate

  get 'papers/pending', to:  'papers#index_pending'
  get 'papers/all',     to:  'papers#index_all'
  get 'papers/refused', to:  'papers#index_refused'
  resources :papers

  resources :categories

  get 'reading_lists/public', to: 'reading_lists#index_public'
  resources :reading_lists

  get 'reading_list_saves/:paper_id',
    to:   'reading_list_saves#save_default',
    :as => :reading_list_save_default
  get 'reading_list_saves/:reading_list_id/:paper_id',
    to:   'reading_list_saves#save',
    :as => :reading_list_save
  get 'reading_list_remove/:reading_list_id/:paper_id',
    to:   'reading_list_saves#remove',
    :as => :reading_list_remove

end

app/models/person.rb
class Person < ApplicationRecord

  attr_accessor :activation_token

  VALID_EMAIL_REGEX = /\A[^@\s]+@([-a-z0-9]+\.)+[a-z]{2,}\z/i

  validates :firstname, presence: true
  validates :lastname, presence: true

  validates :email,
    presence: true,
    format: { with: VALID_EMAIL_REGEX, message: "incorrect format" },
    length: { minimum: 6, maximum: 128 },
    uniqueness: { case_sensitive: false }

  validates :password,
    presence: true,
    length: { minimum: 8, maximum: 256 },
    on: :create

  # digests the password
  has_secure_password

  before_create :create_activation_digest


  ##################################################
  #    LOGIN
  ##################################################

  # Returns the hash digest of the given string.
  def Person.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Person.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Activates an account.
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  ##################################################
  #    ATTRIBUTES
  ##################################################

  # Get the full name of a person
  # Params:
  # +initials+:: bool  ->   true: J. Smith / false: John Smith
  def full_name(initials = false)
    if (initials)
      firstname[0,1] + '. ' + lastname
    else
      firstname + ' ' + lastname
    end
  end

  ##################################################
  #    PERSON STATUS
  ##################################################

  # Checks if the user has the status editor
  def is_editor?
    status == 'editor' || is_admin?
  end

  # Checks if the user has the status admin
  def is_admin?
    status == 'admin'
  end

  # Checks if the user has the status researcher
  def is_researcher?
    status == 'researcher'
  end

  # Checks if the user has the status researcher
  def is_reader?
    status == 'reader'
  end


  ##################################################
  #    RELATIONS TO PAPERS
  ##################################################

  # for current_user

  ##############
  ### ACCESS ###
  ##############
  def can_read?(paper)
    paper.is_published? ||
       #logged_in? &&
       (self.wrote?(paper) ||
        self.is_editor? ||
        self.is_reviewer_of?(paper))
  end

  # Returns true if the user wrote the paper
  def wrote?(paper)
    Author.where(person_id: id).nil?
    paper.get_authors.include? self
  end

  ##############
  ### PAPERS ###
  ##############

  # Get all the papers written by a person
  def get_papers
    Author.where(person_id: id).map { |write|
      Paper.where(id: write.paper_id).take
    }
  end


  ###############
  ### REVIEWS ###
  ###############

  # Get all the reviews written by a person
  def get_reviews
    Review.where(reviewer_id: id)
  end

  def get_pending_reviews
    Review.where(reviewer_id: id).where.not(progression: 'done')
  end

  def get_pending_reviews_asked_by_editor
    Review.where(editor_id: id).where.not(progression: 'done')
  end


  # Returns true if the user has to review the paper
  # progression != done
  def should_review?(paper)
    review = paper.get_review_by(self)
    !review.nil? && review.progression == 'pending'
  end

  # Returns true if the user should review the paper
  def is_reviewing?(paper)
    review = paper.get_review_by(self)
    !review.nil? && review.progression == 'ongoing'
  end

  # Returns true if the user reviewed the paper
  def reviewed?(paper)
    review = paper.get_review_by(self)
    !review.nil? && review.progression == 'done'
  end

  # Returns true if the user is reviewer of the paper
  def is_reviewer_of?(paper)
    Review.where(paper_id: paper.id, reviewer_id: id)
  end

  # Returns true if the user is reviewer of the paper
  def is_editor_of?(paper)
    Review.where(paper_id: paper.id, editor_id: id)
  end


  # Returns true if the user is reviewer of the paper
  # FOR THE CURRENT REVIEW-ROUND
  # maybe reviewer with other researchers
  def is_current_reviewer_of?(paper)
    Review.where(
      paper_id: paper.id,
      reviewer_id: id,
      review_round: paper.reviews_count,
    )
  end

  # Returns true if the user is reviewer of the paper
  # FOR THE CURRENT REVIEW-ROUND
  # maybe editor with other editors
  def is_current_editor_of?(paper)
    Review.where(
      paper_id: paper.id,
      editor_id: id,
      review_round: paper.reviews_count,
    )
  end


  # Returns true if the user wrote the review
  def wrote_review?(review)
    review.reviewer_id == id
  end

  # Returns true if the user asked the review
  def asked_review?(review)
    review.editor_id == id
  end


  ####################
  ### READING LIST ###
  ####################

  def has_saved?(paper)
    has_saved_in(paper).count > 0
  end

  def has_saved_in(paper)
    list_ids = ReadingList.where(person_id: id).pluck(:id)
    ReadingListSave.where(reading_list_id: list_ids, paper_id: paper.id)
  end

  def reading_lists
    ReadingList.where(person_id: id).all
  end

  # take the first private reading_list (might be the default one)
  def default_reading_list
    ReadingList.where(person_id: id, visibility: 0).take
  end

  def is_list_owner?(reading_list)
    list = ReadingList.where(id: reading_list.id).take
    list.person_id == id
  end


  private

    # Create the token and digest.
    def create_activation_digest
      self.activation_token  = Person.new_token
      self.activation_digest = Person.digest(activation_token)
      # self.activation_digest = Person.digest(Person.new_token)
    end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # permissions to access
  before_action :logged_in_as_correct_user, only: [:edit, :edit_password, :update, :destroy]
  before_action :is_logged_in, only: [:index]
  before_action :already_logged_in, only: [:new, :create]
  before_action :is_admin, only: [:activate]


  # GET /people
  def index
    if current_user.is_admin?
      @people = Person.all
    elsif current_user.is_editor?
      @people = Person.where.not(status: 'reader').where.not(activated: nil)
    else # is_researcher or reader
      @people = Person.where(status: ['researcher', 'editor']).where.not(activated: nil)
    end
  end

  # GET /people/:id/papers
  def papers
    person = Person.find(params[:id])
    @papers = person.get_papers
    @title = "Papers from #{person.full_name}"
    render :template => 'papers/index'
  end

  # GET /people/1
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # GET /people/1/edit_password
  def edit_password
    @person = current_user
  end

  # PATCH/PUT /people/1/edit_password
  def update_password
    if @person.update(person_params_edit_password)
      redirect_to @person, notice: 'Your profile was successfully updated.'
    else
      render :edit_password
    end
  end

  # POST /people
  def create
    @person = Person.new(person_params)

    if @person.save
      @person.send_activation_email
      flash[:info] = t('people.create.need_activation')
      # flash[:info] += "Activation token: /#{@person.activation_token}/#{CGI.@person.email}"

      # creates a default reading list for the user
      ReadingList.creates(person_id: @person.id, name: 'Your reading List')

      redirect_to root_url # TODO thanks for joining page

      # log_in @person
      # redirect_to @person, notice: 'Thanks for joining us!'
    else
      flash[:error] = t('people.create.error')
      render :new
    end
  end

  # PATCH/PUT /people/1
  def update
    if @person.update(person_params_edit)
      redirect_to @person, notice: t('people.update.success')
    else
      render :edit
    end
  end

  #  ??? PATCH/PUT /people/1
  def update_password
    if @person.update(person_params_edit)
      redirect_to @person, notice: t('people.update.password.success')
    else
      render :edit
    end
  end

  # DELETE /people/1
  def destroy
    @person.destroy
    redirect_to root_path, notice: t('people.delete.success')
  end

  ####################################
  #     ajax
  ####################################

  # GET /people/1/activates
  # called by ajax, return json
  def activate
    @person = Person.find(params[:id])
    if @person.nil?
      redirect_to people_path, notice: t('people.profile.not_found')
    else
      @person.activate
      redirect_to @person, notice: t('people.update.success')
    end
  end


  ####################################
  #     PRIVATE
  ####################################

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # sign up / log in
    def person_params
      params.require(:person).permit(:email, :password, :firstname, :lastname, :status)
    end

    # for editing one’s profile
    def person_params_edit
      params.require(:person).permit(:firstname, :lastname, :status, :bio, :level, :country, :academia_url, :research_gate_url)
    end

    # for modifying password
    def person_params_edit_password
        params.require(:person).permit(:password)
    end

    ### Access rights

    # Confirms a logged-in user.
    def already_logged_in
      if logged_in?
        redirect_to root_path, :flash => { :error => "You are already logged in! Please log out first." }
      end
    end


end

app/helpers/people_helper.rb
module PeopleHelper

  # Get the gravatar for a user
  # Param:
  # +person+:: +Person+
  # +size+::
  def gravatar_for(person, size: 50, class_sup: '')
    # gravatar_id = Digest::MD5::hexdigest(person.email)
    # gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=identicon"
    # image_tag(gravatar_url, alt: "#{person.firstname} #{person.lastname}", class: "gravatar #{class_sup}")
  end

  # Get possibles values for university status
  def possible_uni_status
    ['undergraduate', 'graduate', 'PhD', 'post doc', '?', 'tenured', 'other:', 'not at the university']
  end

  # Get possibles values for website status
  def possible_website_status
    ['reader', 'author', 'writer', 'editor', 'helper']
  end


  # different color for status
  def get_person_status_color(status)
    if status == 'admin'
      'black'
    elsif status == 'editor'
       'blue-grey darken-3'
     elsif status == 'author' || status == 'researcher'
       'blue-grey'
     elsif status == 'reader'
       'blue-grey lighten-4'
    else
      'white'
    end
  end

end

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field col s12">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div class="input-field col s6">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="input-field col s6">
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>


  <div class="input-field col s6">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="input-field col s6">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

<!--
  <div class="input-field col s12">
    <%= f.label :bio %>
    <%= f.text_area :bio, class: "materialize-textarea" %>
  </div>

  <div class="input-field col s4">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="input-field col s4">
    <%= f.label :level %>
    <%= f.text_field :level %>
  </div>

  <div class="input-field col s4">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="input-field col s6">
    <%= f.label :academia_url %>
    <%= f.text_field :academia_url %>
  </div>

  <div class="input-field col s6">
    <%= f.label :research_gate_url %>
    <%= f.text_field :research_gate_url %>
  </div>
-->
  <div class="actions">
    <%= f.submit 'Sign Up', :class => "btn"  %>
  </div>
<% end %>

app/views/people/_form_edit.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> need correction before you can sign up:</h2>
      <ul class="collection">
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h3>Personal details</h3>
<div class="row">
  <div class="input-field col s6">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="input-field col s6">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="input-field col s12">
    <%= f.label "Short biography" %>
    <%= f.text_area :bio, class: "materialize-textarea", length: "1000" %>
  </div>
</div>


<h3>Website related</h3>
<div class="row">

  <div class="input-field col s4">
   <!--  <select class="" name="person[status]">
      <option disabled selected>Please choose an option</option>
      <% possible_website_status.each do |website_status| %>
      <option value="<%= website_status %>"><%= website_status %></option>
      <% end %>
    </select>
    <%= f.label :status %>-->
    <p><span>Your status:</span> <%= @person.status %></p>

    <% if @person.is_editor? || @person.is_reader? %>
    <%= link_to 'Ask to become an editor', contact_path %>
    <% end %>
  </div>

  <div class="input-field col s8">
    <select id="interests" name="person[interests]" multiple>
      <option selected disabled>Please choose one or many options</option>
    <% Category.all.each do |category| %>
      <option value="<%= category.id %>"><%= category.name %></option>
    <% end %>
  </select>
  <label for="interests">Interests</label>
  </div>
</div>



<h3>University life</h3>

<div class="row">
  <div class="input-field col s4">
    <label for="person_university">University</label>
    <input type="text" name="person[university]" id="person_university" />
  </div>

  <div class="input-field col s4">
    <select name="person[level]">
      <option disabled selected>Please choose an option</option>
      <% possible_uni_status.each do |uni_status| %>
      <option value="<%= uni_status %>"><%= uni_status %></option>
      <% end %>
    </select>
    <%= f.label 'University status' %>
  </div>

  <div class="input-field col s4">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>
</div>

<h3>External sites</h3>

<div class="row">
  <div class="input-field col s6">
    <%= f.label :academia_url %>
    <%= f.text_field :academia_url %>
  </div>

  <div class="input-field col s6">
    <%= f.label :research_gate_url %>
    <%= f.text_field :research_gate_url %>
  </div>

</div>


  <div class="actions">
    <%= f.submit 'Validate', :class => "btn"  %>
  </div>

<% end %>

app/views/people/_form_edit_password.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2>There was <%= pluralize(person.errors.count, "error") %>:</h2>
      <ul class="collection">
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">

  <div class="input-field col offset-s3 s6">
    <%= f.label :password, "Current password"%>
    <%= f.password_field :password %>
  </div>

  <div class="input-field col offset-s3 s6">
    <%= f.label :password_new, "New password"%>
    <%= f.password_field :password_new %>
  </div>

  <div class="input-field col offset-s3 s6">
    <%= f.label :password_confirmation, "Confirm the new password" %>
    <%= f.password_field :password_confirmation %>
  </div>

</div>

<div class="row">

  <div class="actions">
    <%= f.submit 'Validate', :class => "btn"  %>
  </div>
</div>
<% end %>

app/views/people/_form_signup.html.erb
<h1>Sign up</h1>

<%= form_for(person, url: signup_path) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> need correction before you can sign up:</h2>
      <ul class="collection">
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">

  <div class="input-field inline col s12 center-align">
    <%= f.label 'Register as a' %>
    <input type="radio" name="person[status]" id="person_status_reader" value="reader">
      <label for="person_status_reader">reader</label>
    <input type="radio" name="person[status]" id="person_status_researcher" value="researcher">
      <label for="person_status_researcherresearcher">researcher</label>
  </div>

  <div class="input-field col s12">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

</div>

<div class="row">

  <div class="input-field col s6">
    <%#= render 'partials/password_advices' %>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="input-field col s6">
    <%= f.label :password_confirmation, "Password Confirmation" %>
    <%= f.password_field :password_confirmation %>
  </div>

</div>

<div class="row">

  <div class="input-field col s6">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="input-field col s6">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

</div>


  <div class="actions">
    <%= f.submit 'Sign Up', :class => "btn"  %>
  </div>

  <p>
    Already have an account ? <%= link_to 'Log in !', login_path %>
  </p>
<% end %>

app/views/people/edit.html.erb
<% provide(:title, "Edit your profile" ) %>

<h1>Edit your profile</h1>

<%= render 'form_edit', person: @person %>

app/views/people/edit_password.html.erb
<% provide(:title, "Edit your password" ) %>

<h1>Edit your password</h1>

<%= render 'form_edit_password', person: @person %>

<%= link_to 'Cancel', @person, :class => "btn" %> |
<%#= link_to 'Back', people_path, :class => "btn" %>

app/views/people/index.html.erb
<% provide(:title, "People list") %>



<h1>
  <% if logged_in? %>
    <% if current_user.is_admin? %> List of all users
    <% elsif current_user.is_editor? %> List of researchers, editors, admins
    <% else %> List of researchers and editors
    <% end %>
  <% end %>
</h1>

<ul class="collection">

  <% @people.each do |person| %>
  <li class="avatar">

    <%= gravatar_for(person, size: 32, class_sup: 'circle') %>

    <%= person.firstname %> <%= person.lastname %>
    <br />

    <%= link_to 'View',
      person,
      class: "btn-flat" %>

    <% unless person.status.blank? %>
      <span class="new badge <%= get_person_status_color(person.status) %>" data-badge-caption=""><%= person.status %></span>
    <% end %>


    <% if logged_in? && current_user.is_admin? %>
      <span class="new badge deep-orange darken-3" data-badge-caption="">
        <a href="<%  %>"></a>
        <%= "Not activated" unless person.activated %>
      </span>
    <% end %>

    <span class="badge"><%= person.email %></span>

  </li>

<% end %>
</ul>

app/views/people/new.html.erb
<% provide(:title, 'Sign up') %>

<%= render 'form_signup', person: @person %>

app/views/people/show.html.erb
<% provide(:title, "#{@person.firstname} #{@person.lastname}") %>


<div class="row">
  <div class="col s3">
    <%= gravatar_for(@person, size: 150)  %>
  </div>

  <div class="col s5">
    <h1 class="header"><%= @person.firstname %> <%= @person.lastname %></h1>
    <%#= @person.email # private %>

    <% unless @person.status.blank? %>
    <h3> <%= @person.status %> </h3>
    <% end %>

    <% unless @person.bio.blank? %>
    <blockquote>
      <%= @person.bio %>
    </blockquote>
    <% end %>
  </div>

  <div class="col s4">

    <% if is_logged_in_user? @person %>

<h2>Manage your profile</h2>

    <p><%= link_to 'Edit profile', edit_person_path(@person), class: "btn" %></p>

    <p><%= link_to 'Change your password', edit_password_path(@person), class: "btn" %></p>

    <p><%= link_to 'Delete profile',
        @person, method: :delete,
        data: { confirm: 'Are you sure?' },
        class: "btn-flat waves-effect waves-red" %></p>
<% end %>

    <div class="center">
      <% unless @person.research_gate_url.blank? %>
      <%= link_to 'ResearchGate', @person.research_gate_url, class: "btn" %>
      <% end %>
      <br /> <br />
      <% unless @person.academia_url.blank? %>
      <%= link_to 'Academia', @person.academia_url, class: "btn" %>
      <% end %>
    </div>

    <p><%= @person.level unless @person.level.blank? %></p>
    <p><%= @person.country unless @person.country.blank? %></p>
  </div>
</div>

<% if logged_in? && current_user.is_admin? && !@person.activated %>
  <%= link_to 'Activate', person_activate_path(@person), class: 'btn red' %>
<% end %>

<% unless @person.get_papers.blank?  %>

    <% if is_logged_in_user?(@person) %>
    <h2>Your papers</h2>
    <%= link_to 'Submit a new paper', new_paper_path, class: "btn-large" %>
    <% else %>
    <h2>Published papers</h2>
    <% end %>

    <%= render 'papers/partials/paper_list', :papers => @person.get_papers %>

<% else %>

    <%= link_to 'Publish a paper', new_paper_path, class: "btn-large" %>

<% end %>