config/routes.rb
HelloApp::Application.routes.draw do

  resources :keywords
  root 'static_pages#home'
  get '/home',  to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/feedback', to: 'static_pages#feedback'
  get '/contact', to: 'static_pages#contact'

  resources :reviews, path: 'papers/:paper_id/reviews'
  get    '/reviews/mine' => 'reviews#mine', :as => :user_reviews
  post   'papers/:paper_id/review_opinion' => 'reviews#validate_opinion', :as => :review_opinion

  get   'papers/:paper_id/accept' => 'reviews#accept', :as => :accept_paper
  get   'papers/:paper_id/refuse' => 'reviews#refuse_notif', :as => :refuse_paper_notif
  post   'papers/:paper_id/refuse' => 'reviews#refuse', :as => :refuse_paper
  get   'papers/:paper_id/ask_revision' => 'reviews#ask_revision_notif', :as => :ask_paper_revision_notif
  post   'papers/:paper_id/ask_revision' => 'reviews#ask_revision', :as => :ask_paper_revision

  get  'papers/:paper_id/finished' => 'papers#signal_edition_finished', :as => :signal_edition_finished

  resources :people
  get   '/people/:id/edit_password' => 'people#edit_password', :as => :edit_password
  post  '/people/:id/edit_password' => 'people#update_password'
  get   '/people/:id/papers' => 'people#papers', :as => :user_papers

  get   '/signup',  to: 'people#new'
  post  '/signup',  to: 'people#create'
  resources :account_activations#, only: [:edit]

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get   '/people/:id/activate' => 'people#activate', :as => :person_activate

  get 'papers/pending', to:  'papers#index_pending'
  get 'papers/all',     to:  'papers#index_all'
  get 'papers/refused', to:  'papers#index_refused'
  resources :papers

  resources :categories

  get 'reading_lists/public', to: 'reading_lists#index_public'
  resources :reading_lists

  get 'reading_list_saves/:paper_id',
    to:   'reading_list_saves#save_default',
    :as => :reading_list_save_default
  get 'reading_list_saves/:reading_list_id/:paper_id',
    to:   'reading_list_saves#save',
    :as => :reading_list_save
  get 'reading_list_remove/:reading_list_id/:paper_id',
    to:   'reading_list_saves#remove',
    :as => :reading_list_remove

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_paper, except: [:mine]
  before_action :set_review , only: [:show, :edit, :update, :destroy]
  
  before_action :is_editor, only: [:validate_opinion]

  # GET /papers/:paper_id/reviews
  # GET /papers/:paper_id/reviews.json
  def index
    @reviews = Review.where(paper_id: @paper.id)
  end

  # GET /reviews/mine
  # GET /reviews/mine.json
  def mine
    @reviews = Review.where(reviewer_id: current_user.id).all
  end

  # GET /papers/:paper_id/reviews/1
  def show
  end


  # GET /papers/:paper_id/reviews/new
  # not used: only from paper/:id/show
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  ###############################################################

  # POST /papers/:paper_id/reviews
  # creates the reviews with a "pending" status
  # Done by EDITOR
  def create
    if (params[:review][:reviewers])
      params[:review][:reviewers].each do |reviewer_id|
        unless reviewer_id.blank?
          @review = Review.create(
            status:         params[:status],
            editor_remarks: params[:editor_remarks],
            paper_id:       params[:paper_id],
            reviewer_id:    reviewer_id,
            editor_id:      current_user.id,
            progression:    'pending'
          )
        end
      end # end loop
    end

    redirect_to paper_path( :id => params[:paper_id]), notice: 'Review was successfully created.'
  end


  def validate_opinion
    status = params[:review][:status]
    @review = new_opinion(status)
    if @review.save
      redirect_to paper_path(
        :id => params[:paper_id]),
        notice: status == 3 ? 'The paper was successfully published.' : 'The paper was refused.'
    end
  end

  # PATCH/PUT /papers/:paper_id/reviews/1
  # update the review
  # Done by REVIEWER
  def update
    # if the review is marked as done
    if @review.update(review_edit_params)
      @review.update(progression: params[:review][:progression] == 'done' ? 'done' : 'ongoing')
      redirect_to @review, notice: 'The review was successfully updated.'
    else
      render :edit
    end
  end


  # DELETE /papers/:paper_id/reviews/1
  def destroy
    @review.destroy
    redirect_to reviews_url, notice: 'The review was successfully deleted.'
  end

  ######## end of a review round ##################

  # GET /papers/1/ask_revision
  def ask_revision_notif
    render :ask_revision
  end

  # POST /papers/1/ask_revision
  def ask_revision
    @review = Review.create(review_of_review_params)
    @review.review_round = @paper.review_count
    @review.editor_id = current_user.id
    @review.reviewer_id = current_user.id
    @review.progression = 'done'
    # @review.editor_remarks = @review.content

    @paper.set_review_round_done
    @paper.add_a_review_round
    @paper.update(need_review: true)
    redirect_to @paper, notice: t('paper.ask_revision')
  end

  # POST /papers/1/accept
  def accept
    @paper.set_review_round_done
    @paper.update(status: 2)
    redirect_to @paper, notice: t('paper.publish')
  end

  # GET /papers/1/refuse
  def refuse_notif
    render :refusal_notif
  end

  # POST /papers/1/refuse
  def refuse
    #editor_remarks
    @review = Review.create(review_of_review_params)
    @review.review_round = @paper.review_count
    @review.editor_id = current_user.id
    @review.reviewer_id = current_user.id
    @review.progression = 'done'
    # @review.editor_remarks = @review.content

    @paper.set_review_round_done
    @paper.update(status: 3)
    redirect_to @paper, notice: t('paper.refuse')
  end

  ####################################################
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end
  def set_paper
    @paper  = Paper.find(params[:paper_id])
  end

  # PARAMS # Never trust parameters from the scary internet, only allow the white list through.

  # For (batch) creation, by editor
  def review_params
    params.require(:review).permit(:reviewers, :status, :editor_remarks)
  end

  # For edition, by reviewer
  def review_edit_params
    params.require(:review).permit(:reviewer, :status, :content, :progression)
  end

  # for opinion papers, by editor
  def review_opinion_params
    params.require(:review).permit(:status, :editor_remarks)
  end

  # editor feedback on opinion papers
  def review_of_review_params
    params.require(:review).permit(:content)
  end

  ####################

  # Create a new review for an opinion
  # +Params+
  # +Status+  2 for accepted, 3 for refused
  def new_opinion(status)
    review = Review.create(
      status:         params[:status],
      editor_remarks: params[:editor_remarks],
      paper_id:       params[:paper_id],
      reviewer_id:    current_user.id,
      editor_id:      current_user.id,
      progression:    'done'
    )
    @paper.set_review_round_done
    if (review.is_accepted) # review -> accepted
      @paper.publish # published accepted
    elsif (review.is_refused) # review -> refused
      @paper.refuse # refused
    end
    review
  end


end

app/helpers/reviews_helper.rb
module ReviewsHelper

    # Get status meaning from number
    def get_review_status(status)
        case status
        when 3 then 'Accepted'
        when 2 then 'Need minor modifications'
        when 1 then 'Need major modifications'
        when 0 then 'Refused'
        else '?'
        end
    end

end

app/views/reviews/partials/_new.html.erb
<%
  # rendered in from papers/show

  # current_reviews = @paper.get_reviews
  possible_reviewers = get_possible_reviewers_for(@paper)
  reviews_count = @paper.count_last_reviews

%>

<% if reviews_count == 0 %>

  The paper is not yet reviewed.

<% elsif reviews_count > 3 %>

  The paper has already <%= reviews_count %> reviews (maximum).

<% else %>

  The paper has currently <%= reviews_count %> reviews.

<% end %>

<% if reviews_count > 0 %>

  <%= link_to "Read the reviews", reviews_path(@paper.id), class: "btn-flat" if current_user.is_editor? %>

<% end %>
<% if reviews_count < 4 %>
  <h3>Ask for reviews</h3>

  <%= form_for Review.new, :url => reviews_path(@paper.id) do |f| %>

    <%= f.label :editor_remarks %>
    <%= f.text_area :editor_remarks, class: "materialize-textarea" %>

    <%= f.label :reviewers %>
    <%= select("review", "reviewers",
          possible_reviewers.collect {|person| [person.full_name, person.id]},
          {prompt: 'Please choose reviewers'},
          {:multiple => true}) %>

    <button type="submit" class="btn color2bg">
      Ask reviews <i class="material-icons right">send</i>
    </button>
  <% end # end form %>

<% end %>

app/views/reviews/partials/_new_opinion.html.erb
<%
  # rendered in from papers/show

  # current_reviews = @paper.get_reviews
%>

  <p class="card-title">Review this paper</p>

  <p class="precision">As an editor, you can review opinion papers.
    To be accepted, this paper should present ... this and that...</p>

  <%= form_for Review.new, :url => review_opinion_path(@paper.id) do |f| %>

    <%= f.label :editor_remarks %>
    <%= f.text_area :editor_remarks, class: "materialize-textarea" %>

    <button type="submit" name="review[status]" value="3" class="btn color2bg">
      Validate paper <i class="material-icons right">done</i>
    </button>

    <button type="submit" name="review[status]" value="0" class="btn red darken-1">
      Refuse paper <i class="material-icons right">clear</i>
    </button>


  <% end %>

app/views/reviews/partials/_review_list.html.erb
<%
  Review.where(editor_id: 11).pluck(:paper_id).uniq.each do |papers_concerned_id|
  paper = Paper.find(papers_concerned_id)
%>

<div class="card">
  <div class="card-content">

    <p class="title">
      <strong>
        <%= link_to paper.title, paper %>
        by <%= paper.get_authors_as_name_list %>
      </strong>
    </p>

    <ul class="collection">
    <% Review.where(editor_id: 11, paper_id: papers_concerned_id).each do |review| %>
    <li>

      <p>
        <% unless current_user.is_editor? %>
        <%= link_to review.progression=='pending' ? 'Start to review' : 'Continue your review',
        review_path(paper.id, review.id),
        class: "waves-effect waves-light btn"  %>
        <% end %>
      </p>

      <i
        title="<%=review.progression%> - <%=get_review_status(review.status)%>"
        class="material-icons <%=review_get_color_status(review.status)%>-text">
        <%= case review.progression
          when 'done' then 'done'
          when 'ongoing' then 'hourglass_full'
          when 'pending' then 'hourglass_empty'
          end
        %>
        </i>

        Asked <%= distance_of_time_in_words(Time.now, review.created_at) %> ago.
        <br />

        <% if review.editor != current_user %>
          Asked by <%= link_to review.editor.full_name, review.editor %> <br />
        <% end %>

        <% if current_user.is_editor? || current_user.is_admin? %>
          Reviewer:
          <%= link_to review.reviewer.full_name, review.reviewer %> <%= "(you)" if review.reviewer == current_user %>
        <% end %>

      </li>
      <% end # each review %>
    </ul>
    
    <% if (paper.all_reviews_done?) %>
      <p>
        <%= link_to "read reviews", reviews_path(paper.id), class: 'btn-flat' %>
        <%= link_to "send feedback #{icon_feedback}".html_safe, ask_paper_revision_notif_path(paper.id), class: 'btn-flat' %>
        <%= link_to "publish #{icon_publish}".html_safe, accept_paper_path(paper.id), class: 'btn-flat' %>
        <%= link_to "refuse #{icon_refuse}".html_safe, refuse_paper_notif_path(paper.id), class: 'btn-flat' %>
      </p>
    <% end %>

  </div>
</div>

<% end # each paper %>

app/views/reviews/partials/_review_list_details.html.erb
<%

 # REVIEW LIST DETAILS: SEEN FROM ARTICLE BY EDITOR AND AUTHOR
 # SEPARATE AND ORDER BY ROUND

%>

<ul class="collapsible" data-collapsible="expandable">
  <% reviews.order(status: :asc).each_with_index do |review, index| %>

  <li>
    <div class="collapsible-header">
      <% unless review.conflict_of_interest.blank? %>
      <i class="material-icons right" title="Conflict of interest">warning</i>
      <% end %>

      <span class="review">
        <a href="<%=review%>">
        <i
          title="<%= "by #{review.reviewer.full_name}" if logged_in? && current_user.is_editor? %>
          <%=review.progression%> - <%=get_review_status(review.status)%>"
          class="material-icons <%=review_get_color_status(review.status)%>-text">
          <%= case review.progression
            when 'done' then 'done'
            when 'ongoing' then 'hourglass_full'
            when 'pending' then 'hourglass_empty'
            end
          %>
          </i>
        </a>
      </span>

      <% if current_user.is_editor? %>
        Reviewer:
        <%= link_to review.reviewer.full_name, review.reviewer %>
        <%= "(you)" if review.reviewer == current_user %>
      <% else %>
        Read review <%= index %>
      <% end %>
    </div> <!-- end header -->

    <div class="collapsible-body">

       <span class="badge right <%= review_get_color_progression(review.progression) %>">
         <%= "progression: #{review.progression}" if review.progression %>
       </span>
       <span class="badge right <%= review_get_color_status(review.status) %>">
         <%= "status: #{review.status}" if review.status %>
       </span>
       <span class="badge right">
         <%= 'Asked on: '+ review.created_at.strftime("%d %B %Y") %>
       </span>

      <p>
        Asked by: <%= link_to review.editor.full_name, review.editor %>
        <%= "(you)" if review.editor == current_user %>
      </p>

      <% unless review.conflict_of_interest.blank? %>
      <p class="right">
        <i class="material-icons">warning</i> <strong>Conflict of interest </strong>
        <%= review.conflict_of_interest %>
      </p>
      <% end %>

      <p>
        <strong>Review</strong>
        <%= review.content unless review.content.blank? %>
      </p>

    </div>
  </li>

  <% end %>
</ul>

app/views/reviews/partials/_short_preview.html.erb
<% # REVIEW SMALL PREVIEW

if reviews.count > 0

%>
<div class="review-short-previews">
  <% reviews.order(:progression, :status).each do |review| %>
  <span class="review">
    <a href="<%= review_path(review.paper.id, review.id) %>">
    <i
      title="<%= logged_in? && current_user.is_editor? ? "by #{review.reviewer.full_name}" : ""%>
      <%=review.progression%> - <%=get_review_status(review.status)%>"
      class="material-icons <%=review_get_color_status(review.status)%>-text">
      <%= case review.progression
        when 'done' then 'done'
        when 'ongoing' then 'hourglass_full'
        when 'pending' then 'hourglass_empty'
        end
      %>
      </i>
    </a>
  </span>
  <% end %>
</div>
<% end %>

app/views/reviews/partials/_validate.html.erb
<div class="center">
  <p> This paper has been reviewed <% @paper.count_last_reviews %> times</p>
  <%= render 'reviews/partials/short_preview', :reviews => @paper.get_last_reviews %>
  <p> It is its <strong><%= (@paper.reviews_count+1).ordinalize %></strong> round. </p>

   <%= link_to "Read the reviews", reviews_path(@paper.id), class: "btn" if current_user.is_editor? %>
  <br />
  <!--Score: <%= @paper.get_reviews_score %> % -->
  <button class="btn-flat"> Ask another reviewer </button>
</div>


<div class="row center">

  <p class="col m4 s12">
    <a href="<%= ask_paper_revision_notif_path(@paper.id) %>" class="btn-flat"
      title="If you estimate the paper needs corrections...">
      Ask a revision <i class="material-icons right color1">send</i>
    </a>
  </p>

  <p class="col m4 s12">
    <a href="<%= accept_paper_path(@paper.id) %>" class="btn-flat waves-effect waves-green"
      title="If the article has already been corrected and can be published in this state">
      Accept the article <i class="material-icons right green-text">done</i>
    </a>
  </p>

  <p class="col m4 s12">
    <a href="<%= refuse_paper_notif_path(@paper.id) %>" class="btn-flat waves-effect waves-red"
      title="If the article, despite corrections, does not bear enough quality to be published">
      Refuse the article <i class="material-icons right red-text">clear</i>
    </a>
  </p>

</div>